version: '3.11'


services:
  connectuser:
    build: .
    command: > 
              sh -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/conuser
